api:
  build: .
  command: python /code/app/src/app.py
  ports:
   - "8082:8082"
  volumes:
   - .:/code
  links:
   - db
  hostname: myappserver
db:
  hostname: postgresqlserver
  image: sameersbn/postgresql:9.6-2
  environment:
     POSTGRESQL_ROOT_PASSWORD: root
     POSTGRESQL_DATABASE: dbname
